#!/bin/sh -efu

name=fit_res
ver=1.1
tag=
DIR="$name-$ver"

rm -rf -- "$DIR"
mkdir "$DIR"
cd "$DIR"

git clone ../../ .
[ "$tag" = "" ]  || git checkout --detach $tag

rm -rf .git .gear

mkdir debian
for f in changelog control copyright rules; do
  sed 's/${ver}/'$ver'/g' ../$f > debian/$f
done

dpkg-buildpackage --build=any

cd ..
rm -rf -- "$DIR"
